"""crete a readme

Revision ID: 22280f56151c
Revises: ed982ccbc6cd
Create Date: 2019-10-03 10:21:37.698529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22280f56151c'
down_revision = 'ed982ccbc6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcription_email'), 'subcription', ['email'], unique=True)
    op.drop_table('votes')
    op.add_column('blogs', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_column('blogs', 'vote')
    op.add_column('comments', sa.Column('comment', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    op.add_column('blogs', sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'posted')
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name='votes_blog_id_fkey'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='votes_comment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    op.drop_index(op.f('ix_subcription_email'), table_name='subcription')
    op.drop_table('subcription')
    # ### end Alembic commands ###
